CC = g++ 

LIBS = -lm

PRG_OBJS= recognize_vision.cpp 

OBJS= recognize_vision.o

recognize_vision: $(OBJS)
	  $(CC)  -o $@ $(OBJS) $(LIBS)

$(OBJS): $(PRG_OBJS)
	$(CC) $(CFLAGS) -c $*.cpp 
	
	
	
	
	
