// Generated by gencpp from file planner_msgs/planning_cmd.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_PLANNING_CMD_H
#define PLANNER_MSGS_MESSAGE_PLANNING_CMD_H

#include <ros/service_traits.h>


#include <planner_msgs/planning_cmdRequest.h>
#include <planner_msgs/planning_cmdResponse.h>


namespace planner_msgs
{

struct planning_cmd
{

typedef planning_cmdRequest Request;
typedef planning_cmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct planning_cmd
} // namespace planner_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planner_msgs::planning_cmd > {
  static const char* value()
  {
    return "f9f6635257061aef8bea97260f4e6a8b";
  }

  static const char* value(const ::planner_msgs::planning_cmd&) { return value(); }
};

template<>
struct DataType< ::planner_msgs::planning_cmd > {
  static const char* value()
  {
    return "planner_msgs/planning_cmd";
  }

  static const char* value(const ::planner_msgs::planning_cmd&) { return value(); }
};


// service_traits::MD5Sum< ::planner_msgs::planning_cmdRequest> should match 
// service_traits::MD5Sum< ::planner_msgs::planning_cmd > 
template<>
struct MD5Sum< ::planner_msgs::planning_cmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::planning_cmd >::value();
  }
  static const char* value(const ::planner_msgs::planning_cmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::planning_cmdRequest> should match 
// service_traits::DataType< ::planner_msgs::planning_cmd > 
template<>
struct DataType< ::planner_msgs::planning_cmdRequest>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::planning_cmd >::value();
  }
  static const char* value(const ::planner_msgs::planning_cmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planner_msgs::planning_cmdResponse> should match 
// service_traits::MD5Sum< ::planner_msgs::planning_cmd > 
template<>
struct MD5Sum< ::planner_msgs::planning_cmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planner_msgs::planning_cmd >::value();
  }
  static const char* value(const ::planner_msgs::planning_cmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planner_msgs::planning_cmdResponse> should match 
// service_traits::DataType< ::planner_msgs::planning_cmd > 
template<>
struct DataType< ::planner_msgs::planning_cmdResponse>
{
  static const char* value()
  {
    return DataType< ::planner_msgs::planning_cmd >::value();
  }
  static const char* value(const ::planner_msgs::planning_cmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_PLANNING_CMD_H
