// Generated by gencpp from file planner_msgs/planning_cmdResponse.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_PLANNING_CMDRESPONSE_H
#define PLANNER_MSGS_MESSAGE_PLANNING_CMDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planner_msgs
{
template <class ContainerAllocator>
struct planning_cmdResponse_
{
  typedef planning_cmdResponse_<ContainerAllocator> Type;

  planning_cmdResponse_()
    : success(false)
    , args()  {
    }
  planning_cmdResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , args(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _args_type;
  _args_type args;





  typedef boost::shared_ptr< ::planner_msgs::planning_cmdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner_msgs::planning_cmdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct planning_cmdResponse_

typedef ::planner_msgs::planning_cmdResponse_<std::allocator<void> > planning_cmdResponse;

typedef boost::shared_ptr< ::planner_msgs::planning_cmdResponse > planning_cmdResponsePtr;
typedef boost::shared_ptr< ::planner_msgs::planning_cmdResponse const> planning_cmdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner_msgs::planning_cmdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner_msgs::planning_cmdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace planner_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'planner_msgs': ['/home/biorobotica/catkin_ws/src/planeacion/planner_msgs/msg', '/home/biorobotica/catkin_ws/src/planeacion/planner_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::planning_cmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::planning_cmdResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::planning_cmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::planning_cmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::planning_cmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::planning_cmdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner_msgs::planning_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "866983ef097d9f8b07290732e0d3ba58";
  }

  static const char* value(const ::planner_msgs::planning_cmdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x866983ef097d9f8bULL;
  static const uint64_t static_value2 = 0x07290732e0d3ba58ULL;
};

template<class ContainerAllocator>
struct DataType< ::planner_msgs::planning_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner_msgs/planning_cmdResponse";
  }

  static const char* value(const ::planner_msgs::planning_cmdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner_msgs::planning_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
string args\n\
";
  }

  static const char* value(const ::planner_msgs::planning_cmdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner_msgs::planning_cmdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.args);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct planning_cmdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner_msgs::planning_cmdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner_msgs::planning_cmdResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "args: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.args);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_PLANNING_CMDRESPONSE_H
