// Generated by gencpp from file planner_msgs/RepeatedSentence.msg
// DO NOT EDIT!


#ifndef PLANNER_MSGS_MESSAGE_REPEATEDSENTENCE_H
#define PLANNER_MSGS_MESSAGE_REPEATEDSENTENCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planner_msgs
{
template <class ContainerAllocator>
struct RepeatedSentence_
{
  typedef RepeatedSentence_<ContainerAllocator> Type;

  RepeatedSentence_()
    : sentence()
    , repeat_time(0)  {
    }
  RepeatedSentence_(const ContainerAllocator& _alloc)
    : sentence(_alloc)
    , repeat_time(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sentence_type;
  _sentence_type sentence;

   typedef int32_t _repeat_time_type;
  _repeat_time_type repeat_time;





  typedef boost::shared_ptr< ::planner_msgs::RepeatedSentence_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner_msgs::RepeatedSentence_<ContainerAllocator> const> ConstPtr;

}; // struct RepeatedSentence_

typedef ::planner_msgs::RepeatedSentence_<std::allocator<void> > RepeatedSentence;

typedef boost::shared_ptr< ::planner_msgs::RepeatedSentence > RepeatedSentencePtr;
typedef boost::shared_ptr< ::planner_msgs::RepeatedSentence const> RepeatedSentenceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner_msgs::RepeatedSentence_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner_msgs::RepeatedSentence_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace planner_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'planner_msgs': ['/home/biorobotica/catkin_ws/src/planeacion/planner_msgs/msg', '/home/biorobotica/catkin_ws/src/planeacion/planner_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::RepeatedSentence_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner_msgs::RepeatedSentence_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::RepeatedSentence_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner_msgs::RepeatedSentence_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::RepeatedSentence_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner_msgs::RepeatedSentence_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner_msgs::RepeatedSentence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "608dcaa9c362c4d6c83fcb8f1b807c83";
  }

  static const char* value(const ::planner_msgs::RepeatedSentence_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x608dcaa9c362c4d6ULL;
  static const uint64_t static_value2 = 0xc83fcb8f1b807c83ULL;
};

template<class ContainerAllocator>
struct DataType< ::planner_msgs::RepeatedSentence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner_msgs/RepeatedSentence";
  }

  static const char* value(const ::planner_msgs::RepeatedSentence_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner_msgs::RepeatedSentence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string sentence\n\
int32 repeat_time\n\
";
  }

  static const char* value(const ::planner_msgs::RepeatedSentence_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner_msgs::RepeatedSentence_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sentence);
      stream.next(m.repeat_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RepeatedSentence_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner_msgs::RepeatedSentence_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner_msgs::RepeatedSentence_<ContainerAllocator>& v)
  {
    s << indent << "sentence: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.sentence);
    s << indent << "repeat_time: ";
    Printer<int32_t>::stream(s, indent + "  ", v.repeat_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MSGS_MESSAGE_REPEATEDSENTENCE_H
